import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_JP } from "next/font/google";
import Header from "../components/Header";
import { cn } from "@/lib/utils";
import NextAuthProvider from "@/provider/next-auth";

const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Saikyo Anki",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          `min-h-screen bg-background font-sans antialiased 
          flex flex-col h-screen overflow-hidden
          ${NotoSansJP.className}`,
        )}
      >
        <Header></Header>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
